apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV0Z1YW1GbmJ6cG5hSEJmVDA5eVZFZFFZMGR5ZUhGTGNXVnRObnBQVmxWd01YTnZUVEJ3Wm5oT01UWndkRzk1IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
