@startuml C2_Context_ToBe
title Диаграмма контейнеров (C2) для системы "CinemaAbyss" (To-Be)

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

' --- АКТОРЫ И ВНЕШНИЕ СИСТЕМЫ ---

Person(user, "Пользователь", "Смотрит фильмы через браузер или мобильное приложение")

System_Ext(ext_payment_gateway, "Платежная система", "Обрабатывает транзакции по банковским картам")
System_Ext(recommendation_system, "Внешняя рекомендательная система", "Предоставляет персонализированные рекомендации фильмов")
System_Ext(blob_storage, "Хранилище фильмов", "Хранит видеофайлы и постеры. [S3]")
System_Ext(ext_online_cinema, "Онлайн-кинотеатры", "Партнеры-поставщики контента")

' --- ГРАНИЦА НАШЕЙ СИСТЕМЫ ---
System_Boundary(cinema_abyss, "Система 'Кинобездна'") {
    Container(frontend_app, "Клиентское приложение", "JavaScript, React/Vue", "SPA-приложение, работающее в браузере пользователя")
    Container(mobile_app, "Мобильное приложение", "Kotlin/Swift", "Нативное мобильное приложение")

    Container(gateway, "API Gateway", "Java, Custom Proxy", "Единая точка входа, проксирование, Strangler Fig Facade")

    Container(auth_service, "Auth Service", "Java + Lightweight framework", "Управление пользователями, аутентификация, авторизация")
    Container(billing_service, "Billing Service", "Java + Lightweight framework", "Управление подписками и покупками")
    Container(catalog_service, "Catalog Service", "Java + Lightweight framework", "Метаданные о фильмах, статьях, актерах")
    Container(user_content_service, "User Content Service", "Java + Lightweight framework", "Управление оценками и комментариями")
    Container(access_service, "Access Service", "Java + Lightweight framework", "Управление правами доступа к контенту")
    Container(events_service, "Events Service", "Java + Lightweight framework", "Принимает события по REST и публикует их в Kafka")

    Container(monolith, "Monolith (Legacy)", "Go", "Старая система, функциональность которой постепенно замещается")

    ContainerDb(common_db, "Legacy DB", "PostgreSQL", "Общая база данных для монолита и мигрирующих сервисов")
    ContainerDb(access_db, "Access DB", "Redis", "Оптимизированное хранилище прав доступа")
    ContainerQueue(kafka, "Kafka", "Apache Kafka", "Брокер для асинхронного обмена событиями")
}

' --- СВЯЗИ (ПО СЦЕНАРИЯМ) ---

' Общее начало всех сценариев
Rel(user, frontend_app, "Использует")
Rel(user, mobile_app, "Использует")
Rel(frontend_app, gateway, "Отправляет запросы", "HTTPS/JSON")
Rel(mobile_app, gateway, "Отправляет запросы", "HTTPS/JSON")


' *** Сценарий: пользователь регистрируется в системе
' Регистрируемся в auth_service через gateway
Rel(gateway, auth_service, "Переадресует запросы", "HTTPS/JSON") 
' Сохраняем данные в БД
Rel(auth_service, common_db, "Сохраняет и читает данные", "TCP/IP PostgresDB")
' Отбрасываем событие UserRegistered
Rel(auth_service, events_service, "Отправляет запросы", "HTTPS/JSON")
Rel(events_service, kafka, "Отправляет сообщение", "Kafka/JSON")

' *** Сценарий: покупка фильма
' Выбираем фильм для записи
Rel(gateway, catalog_service, "Переадресует запросы", "HTTPS/JSON") 
' Покупаем фильм
Rel(gateway, billing_service, "Отправляет запросы", "HTTPS/JSON") 
' Сохраняем данные в БД
Rel(billing_service, common_db, "Сохраняет и читает данные", "TCP/IP PostgresDB") 
' Отбрасываем событие MovieRented
Rel(billing_service, events_service, "Отправляет запросы", "HTTPS/JSON")
'Rel(events_service, kafka, "Отправляет сообщение", "Kafka/JSON")
' Обновляет права на фильмы
Rel(kafka, access_service, "Получает сообщение", "Kafka/JSON")
Rel(access_service, access_db, "Сохраняет данные", "TCP/IP PostgresDB")
' Платеж во внешнюю систему
Rel(billing_service, ext_payment_gateway, "Отправляет запросы", "HTTPS/JSON")

' *** Сценарий: оформление подписки (как покупка фильма, но другое сообщение)
' Пользователь на что-то подписался
'Rel(gateway, billing_service, "Отправляет запросы", "HTTPS/JSON") 
' Сохраняем данные в БД
'Rel(billing_service, common_db, "Сохраняет и читает данные", "TCP/IP PostgresDB") 
' Отбрасываем событие SubscriptionPurchased
'Rel(billing_service, events_service, "Отправляет запросы", "HTTPS/JSON")
'Rel(events_service, kafka, "Отправляет сообщение", "Kafka/JSON")
' Обновляет права на фильмы
'Rel(kafka, access_service, "Получает сообщение", "Kafka/JSON")
'Rel(access_service, access_db, "Сохраняет данные", "TCP/IP PostgresDB")
' Платеж во внешнюю систему
'Rel(billing_service, ext_payment_gateway, "Отправляет запросы", "HTTPS/JSON")

' *** Сценарий: смотреть фильм
' Выбираем фильм для просмотра
' Rel(gateway, catalog_service, "Переадресует запросы", "HTTPS/JSON") 
' Проверяем права доступа на фильм
Rel(gateway, access_service, "Отправляет запросы", "HTTPS/JSON") 
' Смотрим фильм
Rel(gateway, blob_storage, "Отправляет запросы", "TCP") 

' *** Сценарий: выбор фильма (читать рекомендации, читать статьи, просматривать карточки фильма)
' Просматриваем фильмы
' Rel(gateway, catalog_service, "Переадресует запросы", "HTTPS/JSON") 

' *** Сценарий: оценить фильм
' Просматриваем фильмы
' Rel(gateway, catalog_service, "Переадресует запросы", "HTTPS/JSON") 
' Ставит оценку
Rel(gateway, user_content_service, "Отправляет запросы", "HTTPS/JSON") 
' Отбрасываем событие MovieRated
Rel(user_content_service, events_service, "Отправляет запросы", "HTTPS/JSON")
'Rel(events_service, kafka, "Отправляет сообщение", "Kafka/JSON")

' --- СВЯЗИ (ПО СЛУЖЕБНЫМ ПРОЦЕССАМ) ---
' *** Процесс: Обновляем данные из внешней рекомендательной системы
' ? вопрос, там реббит во внешней системе - прописываем подробно?
Rel(catalog_service, recommendation_system, "Отправляет запросы", "???")

' *** Процесс: Обновляем данные из онлайн-кинотеатров
Rel(catalog_service, ext_online_cinema, "Отправляет запросы", "HTTPS/JSON")

@enduml